# -*- mode: python ; coding: utf-8 -*-

block_cipher = None

a = Analysis(
    ['run.py'],
    pathex=[],
    binaries=[],
    datas=[
        ('templates', 'templates'),
        ('static', 'static'),
        ('env.example', '.'),
        ('requirements.txt', '.'),
        ('README.md', '.'),
        ('DEPLOYMENT.md', '.'),
    ],
    hiddenimports=[
        'flask',
        'flask_sqlalchemy',
        'flask_login',
        'sqlalchemy',
        'aiohttp',
        'msal',
        'google.auth',
        'google.auth.oauthlib',
        'google.auth.httplib2',
        'selenium',
        'playwright',
        'openai',
        'loguru',
        'email_validator',
        'cryptography',
        'bcrypt',
        'pydantic',
        'python_dotenv',
        'aiofiles',
        'chardet',
        'schedule',
        'pytest',
        'pytest_asyncio',
        'black',
        'flake8',
        'email_service',
        'auth',
        'automation',
        'ai',
        'utils',
        'config',
        'database',
        'main',
        'run',
        'task',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='EmailMassSender',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon='static/favicon.ico' if os.path.exists('static/favicon.ico') else None,
)
